__name__ = 'ManaTracker'
__version__ = '0.1.0'
__author__ = 'Dan Regan'
__author_email__ = 'dan@regan-analytics.com'
__description__ = 'Randomizer Tracker App built on C# and Python'
__url__ = 'https://gitlab.com/regananalytics/ManaTracker'
__license__ = 'MIT'